version: '3.9'

volumes:
    postgres_data:

services:
  db:
    image: postgres:14-alpine
    ports:
      - 15432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
      - ./initial.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_USER=gabumas
      - POSTGRES_DB=gabumas

  butcher_app:
    container_name: butcher_app
    build:
      context: ./
    image: butcher
    ports:
      - 8888:8888
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_USER=gabumas
      - POSTGRES_DB=gabumas
