version: '3.9'

x-common-variables: &common-variables
  - POSTGRES_HOST=db
  - POSTGRES_PORT=5432
  - POSTGRES_PASSWORD=pass1234
  - POSTGRES_USER=gabumas
  - POSTGRES_DB=gabumas

volumes:
    postgres_data:

services:
  db:
    container_name: butcher_db
    image: postgres:14-alpine
#    ports:
#      - 15432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
      - ./initial.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      *common-variables

  butcher_app:
    container_name: butcher_app
    build:
      context: ./
    image: butcher
    ports:
      - 8888:8888
    depends_on:
      - db
    environment:
      *common-variables
